apiVersion: v1
kind: Service
metadata:
  name: insurance-app-service
spec:
  selector:
    app: insurance-prediction     # should match label in Deployment
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501            # Streamlit port
  type: NodePort
